<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <arcadeservicesGitCommitHash>94bf4ed94375578cbf8b9c28451dddbb44f0842b</arcadeservicesGitCommitHash>
    <arcadeservicesOutputPackageVersion>1.1.0-beta.23566.3</arcadeservicesOutputPackageVersion>
    <dncengGitCommitHash>ecbbe4d2600067b73aa5f7ccad6d80dbd8ebfcf1</dncengGitCommitHash>
    <dncengOutputPackageVersion>1.1.0-beta.23565.1</dncengOutputPackageVersion>
    <dncengsharedGitCommitHash>8f837017ac05ea8638e247a5866e57402f439a1b</dncengsharedGitCommitHash>
    <dncengsharedOutputPackageVersion>1.1.0-beta.23523.2</dncengsharedOutputPackageVersion>
  </PropertyGroup>
</Project>