<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <GitCommitHash>8b3e188ef7809b5fc208d2ba612afd77d79b9b8f</GitCommitHash>
    <OfficialBuildId>20241010.1</OfficialBuildId>
    <OutputPackageVersion>2.1.0</OutputPackageVersion>
    <PreReleaseVersionLabel></PreReleaseVersionLabel>
    <IsStable>true</IsStable>
  </PropertyGroup>
</Project>